spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
---
spring:
  profiles:
    - local
    - test
  jpa:
    database: h2
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE